# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Deploy website
          uses: JamesIves/github-pages-deploy-action@4.1.0
          with:
              branch: production
              folder: build
